version: '3'
services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - 3001:3010

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - 3002:3020

  service3:
    build:
      context: ./service3
      dockerfile: Dockerfile
    ports:
      - 3003:3030
